format = "[❯](blue)$conda$directory[❯](green)$git_branch(red)$git_status[❯](red)$golang$nodejs$rust$python[❯](fg:#86BBD8)$docker_context[❯](purple)"

add_newline	= false
[directory]
truncate_to_repo = false
truncation_length = 255
style = "bright-blue"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

format = '[ $symbol ($version) ]($style)'
[docker_context]
symbol = " "
format = '[ $symbol $context ]($style) $path'
[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'
[git_status]
format = '[$all_status$ahead_behind ]($style)'
[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'
[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'
[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'
[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "orange"
[conda]
format = '\[[$symbol$environment]($style)\]'
style = "orange"