format = """
$conda\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

add_newline	= false

[directory]
truncate_to_repo = false
truncation_length = 255
style = "bright-blue"

[character]
success_symbol = "[»](purple)"
error_symbol = "[»](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = '\([$branch]($style)\)'
style = "bright-red"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-green"

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "orange"

[conda]
format = '\[[$symbol$environment]($style)\]'
style = "orange"

[nodejs]
format = '\[[$symbol($version)]($style)\]'
style = "green"
