#!/usr/bin/env zsh

##? juno - open a Jupyter notebook

if [[ -n "$1" ]]; then
  cd "$1"
else
  local JUPYTER_HOME="${JUPYTER_HOME:-${XDG_PROJECTS_DIR:-$HOME/Projects}/jupyter}"
  [[ -d $JUPYTER_HOME ]] || mkdir -p ${JUPYTER_HOME}
  cd "$JUPYTER_HOME"
fi
jupyter notebook
